python utils/convert_llava_779k_to_parquet.py \
  --hf_dataset lmms-lab/LLaVA-NeXT-Data \
  --split train \
  --output_dir /ppio_net0/datasets/parquet/llava_779k_demo_10000 \
  --image_col image \
  --messages_col conversations \
  --row_error_mode skip \
  --num_workers 32 \
  --batch_size 1024 \
  --rows_per_file 10000 \
  --max_samples 10000 \
  --write_llamafactory_info
